import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import Banner from '../components/Banner';
import SmallCard from '../components/SmallCard';
import MediumCard from '../components/MediumCard';
import LargeCard from '../components/LargeCard';
import Footer from '../components/Footer';

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  
  
 
  return (
    <>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      {/* Header */}
      <Header/>

      {/* Banner */}
      <Banner/>

      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>

          {/* Pull some data from a server */}
          <div className='grid grid-cols-1 sm:grid-cols-2
          lg:grid-cols-3 xl:grid-cols-4'>
            {data.exploreData?.map((item) =>{
              return <SmallCard img={item.img} distance={item.distance}
              location={item.location} key={item.img}/>
            })}
          </div>
        </section>


        <section>
          <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>


          <div className='flex space-x-3 overflow-scroll 
          scrollbar-hide p-3 -ml-3'>
            {data.cardsData?.map((item) =>{
              return <MediumCard key={item.img} img={item.img} 
              title={item.title} />
            })}
          </div>
        </section>

        <LargeCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Wishlists curated by AirBnb."
          buttonText="Get Inspired"
        />
      </main>

      {/* Footer */}
      <Footer/>

      
    </>
  )
}


export async function getStaticProps(){
  const data = await fetch('https://airbnb-vercel-server.vercel.app/exploredata')
  .then((res) => res.json())
  
  
  return{
    props:{
       data,
    }
  }
}